# lable결정

In [24]:
import pandas as pd
ori_data = pd.read_csv("responses.csv")
data = ori_data
data.head()

,Music,Slow songs or fast songs,Dance,Folk,Country,Classical music,Musical,Pop,Rock,Metal or Hardrock,...,Age,Height,Weight,Number of siblings,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
0,5.0,3.0,2.0,1.0,2.0,2.0,1.0,5.0,5.0,1.0,...,20.0,163.0,48.0,1.0,female,right handed,college/bachelor degree,no,village,block of flats
1,4.0,4.0,2.0,1.0,1.0,1.0,2.0,3.0,5.0,4.0,...,19.0,163.0,58.0,2.0,female,right handed,college/bachelor degree,no,city,block of flats
2,5.0,5.0,2.0,2.0,3.0,4.0,5.0,3.0,5.0,3.0,...,20.0,176.0,67.0,2.0,female,right handed,secondary school,no,city,block of flats
3,5.0,3.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,...,22.0,172.0,59.0,1.0,female,right handed,college/bachelor degree,yes,city,house/bungalow
4,5.0,3.0,4.0,3.0,2.0,4.0,3.0,5.0,3.0,1.0,...,20.0,170.0,59.0,1.0,female,right handed,secondary school,no,village,house/bungalow

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Columns: 150 entries, Music to House - block of flats
dtypes: float64(134), int64(5), object(11)
memory usage: 1.2+ MB

In [13]:
data.describe()

,Music,Slow songs or fast songs,Dance,Folk,Country,Classical music,Musical,Pop,Rock,Metal or Hardrock,...,Shopping centres,Branded clothing,Entertainment spending,Spending on looks,Spending on gadgets,Spending on healthy eating,Age,Height,Weight,Number of siblings
count,1007.000000,1008.000000,1006.000000,1005.000000,1005.000000,1003.000000,1008.000000,1007.000000,1004.000000,1007.000000,...,1008.000000,1008.000000,1007.000000,1007.000000,1010.000000,1008.00000,1003.000000,990.000000,990.000000,1004.000000
mean,4.731877,3.328373,3.113320,2.288557,2.123383,2.956132,2.761905,3.471698,3.761952,2.361470,...,3.234127,3.050595,3.201589,3.106256,2.870297,3.55754,20.433699,173.514141,66.405051,1.297809
std,0.664049,0.833931,1.170568,1.138916,1.076136,1.252570,1.260845,1.161400,1.184861,1.372995,...,1.323062,1.306321,1.188947,1.205368,1.284970,1.09375,2.828840,10.024505,13.839561,1.013348
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,15.000000,62.000000,41.000000,0.000000
25%,5.000000,3.000000,2.000000,1.000000,1.000000,2.000000,2.000000,3.000000,3.000000,1.000000,...,2.000000,2.000000,2.000000,2.000000,2.000000,3.00000,19.000000,167.000000,55.000000,1.000000
50%,5.000000,3.000000,3.000000,2.000000,2.000000,3.000000,3.000000,4.000000,4.000000,2.000000,...,3.000000,3.000000,3.000000,3.000000,3.000000,4.00000,20.000000,173.000000,64.000000,1.000000
75%,5.000000,4.000000,4.000000,3.000000,3.000000,4.000000,4.000000,4.000000,5.000000,3.000000,...,4.000000,4.000000,4.000000,4.000000,4.000000,4.00000,22.000000,180.000000,75.000000,2.000000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.00000,30.000000,203.000000,165.000000,10.000000

In [17]:
corr_matrix = data.corr()
corr_matrix["Music"].sort_values(ascending=True)

Weight                           -0.130746
Eating to survive                -0.081713
Age                              -0.076829
Politics                         -0.072768
Mathematics                      -0.069702
Height                           -0.068953
Physics                          -0.068848
Western                          -0.063580
Gardening                        -0.046249
Prioritising workload            -0.045614
Fake                             -0.042723
Heights                          -0.042436
Documentary                      -0.038650
War                              -0.035345
Law                              -0.033674
Finances                         -0.032529
Charity                          -0.029594
Economy Management               -0.025346
Horror                           -0.025005
God                              -0.023091
Flying                           -0.022756
Religion                         -0.019674
Responding to a serious letter   -0.019016
Small - big dogs                 -0.013771
Dangerous dogs                   -0.013741
Number of siblings               -0.009812
Country                          -0.007589
Dreams                           -0.007224
Cars                             -0.006673
Hypochondria                     -0.006468
                                    ...
Judgment calls                    0.078130
Pop                               0.079583
Comedy                            0.080313
Dance                             0.081572
Socializing                       0.083740
Questionnaires or polls           0.084712
Animated                          0.086014
Getting up                        0.088511
Musical instruments               0.092307
Theatre                           0.093231
Spending on looks                 0.093457
Swing, Jazz                       0.096121
Dancing                           0.097411
Interests or hobbies              0.097759
Shopping centres                  0.098186
Slow songs or fast songs          0.100207
Empathy                           0.102720
Number of friends                 0.104106
Rock n roll                       0.110524
Appearence and gestures           0.111217
Compassion to animals             0.112660
Shopping                          0.116078
Fantasy/Fairy tales               0.122020
Alternative                       0.124168
Foreign languages                 0.143989
Internet                          0.146442
Rock                              0.165995
Movies                            0.208587
Fun with friends                  0.228092
Music                             1.000000
Name: Music, Length: 139, dtype: float64

In [21]:
corr_matrix["Age"].sort_values(ascending=True)

Changing the past         -0.147357
Shopping centres          -0.133868
Questionnaires or polls   -0.126586
Getting up                -0.119694
Mood swings               -0.111618
Cheating in school        -0.107587
Animated                  -0.101916
Foreign languages         -0.096988
Shopping                  -0.095809
Chemistry                 -0.077257
Music                     -0.076829
Spiders                   -0.076575
Spending on looks         -0.072659
Branded clothing          -0.066279
Loneliness                -0.066186
Comedy                    -0.066016
Fun with friends          -0.065944
Romantic                  -0.065062
Sci-fi                    -0.064702
Hiphop, Rap               -0.063344
Appearence and gestures   -0.060721
Biology                   -0.056772
Self-criticism            -0.053260
Life struggles            -0.053163
Darkness                  -0.047962
Hypochondria              -0.046140
Dreams                    -0.044136
Parents' advice           -0.041518
Fear of public speaking   -0.040828
Unpopularity              -0.040713
                             ...
Cars                       0.069942
Country                    0.073303
Countryside, outdoors      0.073580
Thinking ahead             0.074108
Geography                  0.077973
Latino                     0.078273
Personality                0.079009
Economy Management         0.082876
Politics                   0.086868
Number of siblings         0.090374
Western                    0.099778
Daily events               0.101652
Gardening                  0.102679
History                    0.106643
Physics                    0.109662
Science and technology     0.111303
Workaholism                0.111755
Writing notes              0.112248
Height                     0.114841
Charity                    0.120679
Opera                      0.121448
Thriller                   0.122049
PC                         0.126422
Documentary                0.127948
Folk                       0.133230
Reliability                0.149741
Prioritising workload      0.154959
Elections                  0.212104
Weight                     0.237722
Age                        1.000000
Name: Age, Length: 139, dtype: float64

In [29]:
corr_matrix["Spending on gadgets"].sort_values(ascending=True)

Life struggles                   -0.211767
Folk                             -0.155887
Reading                          -0.150605
Empathy                          -0.143804
Dangerous dogs                   -0.136862
Flying                           -0.131646
Storm                            -0.126367
Fantasy/Fairy tales              -0.122089
Romantic                         -0.114039
Latino                           -0.107433
Decision making                  -0.104983
Darkness                         -0.100194
Finances                         -0.097290
Unpopularity                     -0.096258
Children                         -0.095628
Responding to a serious letter   -0.092315
God                              -0.089195
Chemistry                        -0.084098
Musical                          -0.075305
Writing notes                    -0.075244
Heights                          -0.071972
Religion                         -0.069739
Countryside, outdoors            -0.068239
Psychology                       -0.068144
Medicine                         -0.064575
Gardening                        -0.063805
Rats                             -0.063411
Documentary                      -0.062566
Mood swings                      -0.062441
Snakes                           -0.061852
                                    ...
Small - big dogs                  0.128422
Energy levels                     0.128489
Economy Management                0.128873
Achievements                      0.131491
Movies                            0.131706
Active sport                      0.131968
Physics                           0.132788
Hiphop, Rap                       0.145536
Techno, Trance                    0.154861
Shopping centres                  0.155511
Number of friends                 0.158597
Criminal damage                   0.159182
Funniness                         0.164704
Horror                            0.165369
Sci-fi                            0.172885
Thriller                          0.176993
Adrenaline sports                 0.218166
Height                            0.227769
Action                            0.234132
Spending on healthy eating        0.235251
Knowing the right people          0.240060
Weight                            0.244183
Internet                          0.248663
Science and technology            0.286556
Cars                              0.298234
PC                                0.324356
Spending on looks                 0.334428
Entertainment spending            0.336616
Branded clothing                  0.352667
Spending on gadgets               1.000000
Name: Spending on gadgets, Length: 139, dtype: float64

In [35]:
corr_matrix["Number of siblings"].sort_values(ascending=True)

Loss of interest             -0.088395
Spending on healthy eating   -0.082345
Celebrities                  -0.078784
Shopping                     -0.067315
Shopping centres             -0.064048
Borrowed stuff               -0.061461
Pets                         -0.061324
Getting up                   -0.059854
Public speaking              -0.058942
Pop                          -0.057928
Compassion to animals        -0.053902
Appearence and gestures      -0.051127
Law                          -0.048811
Spiders                      -0.047102
Fear of public speaking      -0.047073
Comedy                       -0.046060
Reliability                  -0.045406
Spending on looks            -0.041896
Heights                      -0.041723
Finances                     -0.039973
Branded clothing             -0.039901
Healthy eating               -0.038847
Mood swings                  -0.038456
Hiphop, Rap                  -0.036785
Fake                         -0.036577
Flying                       -0.036479
Darkness                     -0.034174
Thinking ahead               -0.031021
Economy Management           -0.030031
History                      -0.028279
                                ...
Biology                       0.046746
Decision making               0.047941
Dangerous dogs                0.047985
Interests or hobbies          0.049794
Animated                      0.054582
Charity                       0.054628
Adrenaline sports             0.055152
Western                       0.055694
Physics                       0.057459
PC                            0.058369
Musical                       0.061352
Science and technology        0.061809
Opera                         0.062054
Happiness in life             0.063311
Socializing                   0.063845
Classical music               0.065717
War                           0.067048
Punk                          0.067357
Countryside, outdoors         0.080249
Final judgement               0.083245
Mathematics                   0.084928
Age                           0.090374
Energy levels                 0.090542
Folk                          0.090927
New environment               0.091594
Musical instruments           0.121628
God                           0.133074
Children                      0.144364
Religion                      0.144542
Number of siblings            1.000000
Name: Number of siblings, Length: 139, dtype: float64